projects:
  bucketlisttracker:
    schemaPath: amplify/backend/api/bucketlisttracker/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
      - src/graphql/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/API.ts
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
